module.exports = /** @type {const} */ ({
    "strategy": {
        "1": "Torque control",
        "2": "Torque control / angle monitoring",
        "3": "Torque control / angle control AND",
        "4": "Angle control / torque monitoring",
        "5": "DS control",
        "6": "DS control torque monitoring",
        "7": "Reverse angle",
        "8": "Reverse torque",
        "9": "Click wrench",
        "10": "Rotate spindle forward",
        "11": "Torque control angle control OR",
        "12": "Rotate spindle reverse",
        "13": "Home position forward",
        "14": "EP Monitoring",
        "15": "Yield",
        "16": "EP Fixed",
        "17": "EP Control",
        "18": "EP Angle shutoff",
        "19": "Yield / torque control OR",
        "20": "Snug gradient",
        "21": "Residual torque / Time",
        "22": "Residual torque / Angle",
        "23": "Breakaway peak",
        "24": "Loose and tightening",
        "25": "Home position reverse",
        "26": "PVT comp with Snug",
        "99": "No strategy"
    },
    "strategyOptions": {
        "0": "Torque",
        "1": "Angle",
        "2": "Batch",
        "3": "PVT Monitoring",
        "4": "PVT Compensate",
        "5": "Self-tap",
        "6": "Rundown",
        "7": "CM",
        "8": "DS control",
        "9": "Click Wrench",
        "10": "RBW Monitoring"
    },    
    "tighteningErrorStatus": {
        "0": "Rundown angle max shut off",
        "1": "Rundown angle min shut off",
        "2": "Torque max shut off",
        "3": "Angle max shut off",
        "4": "Self-tap torque max shut off",
        "5": "Self-tap torque min shut off",
        "6": "Prevail torque max shut off",
        "7": "Prevail torque min shut off",
        "8": "Prevail torque compensate overflow",
        "9": "Current monitoring max shut off",
        "10": "Post view torque min torque shut off",
        "11": "Post view torque max torque shut off",
        "12": "Post view torque Angle too small",
        "13": "Trigger lost",
        "14": "Torque less than target",
        "15": "Tool hot",
        "16": "Multistage abort",
        "17": "Rehit",
        "18": "DS measure failed",
        "19": "Current limit reached",
        "20": "End Time out shutoff",
        "21": "Remove fastener limit exceeded",
        "22": "Disable drive",
        "23": "Transducer lost",
        "24": "Transducer shorted",
        "25": "Transducer corrupt",
        "26": "Sync timeout",
        "27": "Dynamic current monitoring min",
        "28": "Dynamic current monitoring max",
        "29": "Angle max monitor",
        "30": "Yield nut off",
        "31": "Yield too few samples"
    },
    "tighteningErrorStatus2": {
        "0": "Drive deactivated",
        "1": "Tool stall",
        "2": "Drive hot",
        "3": "Gradient monitoring high",
        "4": "Gradient monitoring low",
        "5": "Reaction bar failed",
        "6": "Snug Max",
        "7": "Cycle abort",
        "8": "Necking failure",
        "9": "Effective loosening",
        "10": "Over speed",
        "11": "No residual Torque",
        "12": "Positioning fail",
        "13": "Snug Mon. Low",
        "14": "Snug Mon. High",
        "15": "Dynamic Min. Current",
        "16": "Dynamic Mac Current",
        "17": "Latent result",
        "18": "Reserved",
        "19": "Reserved",
        "20": "Reserved",
        "21": "Reserved",
        "22": "Reserved",
        "23": "Reserved",
        "24": "Reserved",
        "25": "Reserved",
        "26": "Reserved",
        "27": "Reserved",
        "28": "Reserved",
        "29": "Reserved",
        "30": "Reserved",
        "32": "Reserved"
    },
    "status": {
        "0": "LOW",
        "1": "OK",
        "2": "HIGH"
    },
    "torqueValuesUnit": {
        "1": "Nm",
        "2": "Lbf.ft",
        "3": "Lbf.In",
        "4": "Kpm",
        "5": "Kgf.cm",
        "6": "ozf.in",
        "7": "%",
        "8": "Ncm"
    },
    "resultType": {
        "1": "Tightening",
        "2": "Loosening",
        "3": "Batch Increment",
        "4": "Batch decrement",
        "5": "Bypass parameter set result",
        "6": "Abort Job result",
        "7": "Sync tightening",
        "8": "Reference setup"
    },
    "serializer-torqueValuesUnit": {
        "Nm": 1,
        "Lbf.ft": 2,
        "Lbf.In": 3,
        "Kpm": 4,
        "Kgf.cm": 5,
        "ozf.in": 6,
        "%": 7,
        "Ncm": 8
    },
    "serializer-resultType": {
        "Tightening": 1,
        "Loosening": 2,
        "Batch Increment": 3,
        "Batch decrement": 4,
        "Bypass parameter set result": 5,
        "Abort Job result": 6,
        "Sync tightening": 7,
        "Reference setup": 8
    },
    "serializer-strategy": {
        "Torque control": 1,
        "Torque control / angle monitoring": 2,
        "Torque control / angle control AND": 3,
        "Angle control / torque monitoring": 4,
        "DS control": 5,
        "DS control torque monitoring": 6,
        "Reverse angle": 7,
        "Reverse torque": 8,
        "Click wrench": 9,
        "Rotate spindle forward": 10,
        "Torque control angle control OR": 11,
        "Rotate spindle reverse": 12,
        "Home position forward": 13,
        "EP Monitoring": 14,
        "Yield": 15,
        "EP Fixed": 16,
        "EP Control": 17,
        "EP Angle shutoff": 18,
        "Yield / torque control OR": 19,
        "Snug gradient": 20,
        "Residual torque / Time": 21,
        "Residual torque / Angle": 22,
        "Breakaway peak": 23,
        "Loose and tightening": 24,
        "Home position reverse": 25,
        "PVT comp with Snug": 26,
        "No strategy": 99
    }
});
