module.exports = /** @type {const} */ ({
    "15": "psetSelected",
    "52": "vin",
    "61": "lastTightening",
    "71": "alarm",
    "74": "alarmAcknowledged",
    "76": "alarmStatus",
    "22": "lockAtBatchDoneUpload",
    "35": "jobInfo",
    "91": "multiSpindleStatus",
    "101": "multiSpindleResult",
    "106": "lastPowerMACSTighteningResultStationData",
    "121": "jobLineControl",
    "152": "multipleIdentifierResultParts",
    "211": "statusExternallyMonitoredInputs",
    "217": "relayFunction",
    "221": "digitalInputFunction",
    "242": "userData",
    "251": "selectorSocketInfo",
    "262": "toolTagID",
    "401": "automaticManualMode",
    "421": "openProtocolCommandsDisabled",
    "501": "motorTuningResultData"
});
